### ISSUE TITLE
quality check the sentiment score

### ISSUE THREAD

**Issue by pablogrr** [petartonchev/weast#22]
check the sentiment score with with sample of data base to make an expert opinion sentiment score and compare to model. provide feedback

**Comment by odeger** [comment]
Received the outcomes of the two models yesterday, working on listing the pros and cons of both models

**Comment by odeger** [comment]
[comparison of 2 models .pdf](https://github.com/petartonchev/weast/files/3898463/comparison.of.2.models.pdf)
