### ISSUE TITLE
Create an informative design that explains the aim of the app 

### ISSUE THREAD

**Issue by petartonchev** [petartonchev/weast#35]
As a user, I would like to have a good understanding of how the app can be used to make decisions about trading, so that I get the most of the tool.

time estimate: 2 hours

**Comment by davidloris** [comment]
[Scanned Documents (1).pdf](https://github.com/petartonchev/weast/files/3961409/Scanned.Documents.1.pdf)

**Comment by davidloris** [comment]
suggested images @mmladenova 

https://www.google.com/search?biw=1440&bih=696&tbm=isch&sxsrf=ACYBGNT2zflpsIGEWJ7xpABgD-lcTVK9ng%3A1576248647505&sa=1&ei=R6XzXdO7Hs_GgQaBhqygBw&q=wall+street+cartoon+trading+sentiment&oq=wall+street+cartoon+trading+sentiment&gs_l=img.3...8799.10078..10210...0.0..0.69.761.12......0....1..gws-wiz-img.......35i39.ZUnnFhp6LPs&ved=0ahUKEwiT-9jl77LmAhVPY8AKHQEDC3QQ4dUDCAc&uact=5#imgrc=ChX89MNHrlCa9M:



https://www.google.com/search?biw=1440&bih=696&tbm=isch&sxsrf=ACYBGNS9ZYpYZjvqnJ6u6CLv0Qc0WVTeBw%3A1576248738417&sa=1&ei=oqXzXfWCGZipgAbKvbTADw&q=stock+sentiment+.+cartoon&oq=stock+sentiment+.+cartoon&gs_l=img.3...5226.6425..6741...0.0..0.76.723.11......0....1..gws-wiz-img.......35i39j0i8i30j0i24j0i30.vJsHhciITvQ&ved=0ahUKEwj124WR8LLmAhWYFMAKHcoeDfgQ4dUDCAc&uact=5#imgrc=99pl9jdn0wx3RM:

**Comment by davidloris** [comment]
@mmladenova 

Suggested USPS:

- accurate sentiment analysis using deep learning algorithms
- easily monitor the sentiment of your stocks
- visualizr the sentiment trends against stock prices
