### ISSUE TITLE
Create a visualization showing the sentiment sector-wise

### ISSUE THREAD

**Issue by petartonchev** [petartonchev/weast#40]
Something like that but with the sentiment of the whole sector not just zoomed out version (if possible)

<img width="719" alt="Screenshot 2019-11-28 at 15 56 23" src="https://user-images.githubusercontent.com/19142553/69887445-3be79700-12e7-11ea-8c8a-5c0e0f0e1834.png">
<img width="690" alt="Screenshot 2019-11-28 at 15 56 31" src="https://user-images.githubusercontent.com/19142553/69887446-3be79700-12e7-11ea-8b2d-fa56f2097c23.png">

**Comment by davidloris** [comment]
@petartonchev looks good but could we have less decimal points when you hover over?
